const moviesMock = [{"id":"a2a5111e-d2e8-41d3-ab6f-e45d9e052f5e","title":"Dark Command","year":2003,"cover":"http://dummyimage.com/138x240.jpg/5fa2dd/ffffff","description":"Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.","duration":1964,"contentRating":"","source":"https://skype.com/orci.jsp","tag":["Drama","Comedy|Drama","Crime|Drama","Western"]},
{"id":"9461bb4d-c39e-4719-8b1f-55a8f1818ef4","title":"Rebellion (L'ordre et la morale)","year":1996,"cover":"http://dummyimage.com/154x102.png/ff4444/ffffff","description":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","duration":2026,"contentRating":"NC-17","source":"http://mtv.com/ipsum/integer/a.png","tag":["Animation|Children|Comedy","Drama|Romance"]},
{"id":"bf7d264c-39f7-4e12-bd17-a63fd1a2063d","title":"Killjoy 3","year":1995,"cover":"http://dummyimage.com/204x197.bmp/dddddd/000000","description":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","duration":1992,"contentRating":"PG","source":"http://fema.gov/dapibus.aspx","tag":["Documentary|War"]},
{"id":"3b707b79-6c62-4044-891e-4b25f9d68d1d","title":"Carefree","year":2004,"cover":"http://dummyimage.com/164x186.bmp/cc0000/ffffff","description":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.","duration":1911,"contentRating":"PG","source":"http://soup.io/donec/semper/sapien/a/libero/nam/dui.png","tag":["Crime|Drama","Drama","Action|Drama","Action|Thriller","Documentary"]},
{"id":"8e3caa55-cc4f-4555-973f-6e3420b9725a","title":"Expendables 2, The","year":1994,"cover":"http://dummyimage.com/159x110.bmp/cc0000/ffffff","description":"Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.","duration":1925,"contentRating":"G","source":"https://hhs.gov/habitasse.jpg","tag":["Drama|Romance","Comedy|Horror|Romance|Sci-Fi","Comedy","Action|Crime"]},
{"id":"efa439f6-d707-4793-8741-235d6d888b63","title":"Circles (Krugovi)","year":1996,"cover":"http://dummyimage.com/147x135.jpg/dddddd/000000","description":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","duration":2040,"contentRating":"PG-13","source":"http://hud.gov/venenatis/non.aspx","tag":["Documentary","Comedy|Romance","Documentary","Adventure|Drama|Horror|Mystery"]},
{"id":"3aed6132-e41c-4cbf-bc44-71dce39fcffc","title":"Diary of a Hitman","year":2011,"cover":"http://dummyimage.com/144x168.bmp/cc0000/ffffff","description":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.","duration":1997,"contentRating":"R","source":"http://state.tx.us/leo/odio/condimentum/id.js","tag":["Drama","Comedy|Musical|Romance","Drama|Thriller","Action|Adventure|Comedy"]},
{"id":"4b8f082e-0a73-4abf-96d8-0b9f85a42de0","title":"Trap, The (Klopka)","year":2010,"cover":"http://dummyimage.com/150x181.jpg/5fa2dd/ffffff","description":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.","duration":2065,"contentRating":"","source":"https://wix.com/sit/amet/eros/suspendisse.jsp","tag":["Documentary","Drama|Romance"]},
{"id":"927150eb-d2af-440b-8277-5bc01887f0d5","title":"Suicide Kings","year":1992,"cover":"http://dummyimage.com/126x163.jpg/dddddd/000000","description":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.","duration":1949,"contentRating":"NC-17","source":"https://themeforest.net/dis/parturient/montes/nascetur/ridiculus/mus/etiam.html","tag":["Comedy","Comedy|Crime|Romance"]},
{"id":"bf356ead-32c9-423e-ac65-4d4122350b93","title":"Burning Secret","year":1998,"cover":"http://dummyimage.com/189x194.png/cc0000/ffffff","description":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","duration":1949,"contentRating":"G","source":"https://cdc.gov/natoque/penatibus/et.png","tag":["Drama","Adventure|Drama|War","Drama"]}]

module.exports = {
    moviesMock
}